# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='sure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
