# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0002_auto_20170522_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teklif',
            old_name='kabul_durumu',
            new_name='onay_durumu',
        ),
    ]
