# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0003_auto_20170522_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teklif',
            old_name='kullanici',
            new_name='teklif_veren',
        ),
    ]
