# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0005_auto_20170522_1527'),
        ('teklif', '0004_auto_20170522_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifOnay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay_durumu', models.BooleanField(default=True)),
                ('onay_tarihi', models.DateTimeField(auto_now_add=True)),
                ('teklif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teklif_onay', to='ilan.Ilan')),
            ],
            options={
                'verbose_name_plural': 'Teklif Onayları',
                'verbose_name': 'Teklif Onayı',
            },
        ),
    ]
