# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0008_auto_20170522_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='teklif_veren',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_arayan', to='kullanici.IsArayan'),
        ),
        migrations.AlterField(
            model_name='teklifonay',
            name='teklif',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teklif_onay', to='teklif.Teklif'),
            preserve_default=False,
        ),
    ]
