# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hizmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsArayan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True)),
                ('isArayanTipi', models.CharField(blank=True, choices=[('S', 'Şirket'), ('B', 'Bireysel')], max_length=1, null=True)),
                ('dogumGunu', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('telefon', models.CharField(blank=True, max_length=12, null=True)),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='kullanicilar')),
                ('hizmetler', models.ManyToManyField(related_name='hizmetler', to='hizmet.Hizmet')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_arayan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'İş Veren  Profilleri',
                'verbose_name': 'İş Veren Profili',
            },
        ),
        migrations.CreateModel(
            name='IsVeren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1, null=True)),
                ('dogumGunu', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('telefon', models.CharField(blank=True, max_length=12, null=True)),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='users')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_veren', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'verbose_name': 'İş Veren Profili',
            },
        ),
    ]
