# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isarayan',
            options={'verbose_name': 'İş Arayan Profili', 'verbose_name_plural': 'İş Arayan  Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='isveren',
            options={'verbose_name': 'İş Veren Profili', 'verbose_name_plural': 'İş Veren Profilleri'},
        ),
    ]
