# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kullanici', '0002_auto_20170522_1427'),
        ('adres', '0002_auto_20170522_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_basligi', models.CharField(max_length=40)),
                ('sure', models.CharField(max_length=40)),
                ('butce', models.CharField(max_length=40)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_veren_adresi', to='adres.Adres')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_veren', to='kullanici.IsVeren')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
    ]
