# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_auto_20170522_1427'),
        ('adres', '0002_auto_20170522_1448'),
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_basligi', models.CharField(max_length=40)),
                ('sure', models.CharField(max_length=40)),
                ('butce', models.CharField(max_length=40)),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenlenme_tarihi', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'İlanlar',
                'verbose_name': 'İlan',
            },
        ),
        migrations.RemoveField(
            model_name='adres',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='kullanici',
        ),
        migrations.DeleteModel(
            name='Adres',
        ),
        migrations.AddField(
            model_name='ilan',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_veren_adresi', to='adres.Adres'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_veren', to='kullanici.IsVeren'),
        ),
    ]
