# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0002_auto_20170522_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_veren_adresi', to='adres.Adres'),
        ),
    ]
