# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0003_auto_20170522_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='butceTipi',
            field=models.CharField(choices=[('TL', 'Türk Lirası'), ('DLR', 'DOLAR'), ('EUR', 'EURO')], default='TL', max_length=3),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='butce',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sure',
            field=models.IntegerField(max_length=40),
        ),
    ]
