# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_auto_20170522_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='butce',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sure',
            field=models.IntegerField(),
        ),
    ]
