# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0002_auto_20170522_1310'),
        ('ilan', '0007_auto_20170522_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='hizmet',
            field=models.ManyToManyField(blank=True, null=True, related_name='hizmet_kategorisi', to='hizmet.Hizmet'),
        ),
    ]
