# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0008_ilan_hizmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='hizmet',
            field=models.ManyToManyField(related_name='hizmet_kategorisi', to='hizmet.Hizmet'),
        ),
    ]
