# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0002_auto_20170522_1310'),
        ('ilan', '0010_auto_20170523_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='hizmetDescr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hizmet_descr', to='hizmet.HizmetDescription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilan',
            name='hizmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hizmet_tipi', to='hizmet.Hizmet'),
        ),
    ]
