# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HizmetDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmetBasligi', models.CharField(max_length=50)),
                ('yolMasrafi', models.BooleanField(default=True)),
                ('yemekMasrafi', models.BooleanField(default=True)),
                ('calismaTipi', models.CharField(blank=True, choices=[('U', 'Uzaktan'), ('A', 'Çalışma Alanında')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hizmetler',
                'verbose_name': 'Hizmet',
            },
        ),
        migrations.AlterModelOptions(
            name='hizmet',
            options={'verbose_name': 'Hizmet Türü', 'verbose_name_plural': 'Hizmet Türleri'},
        ),
        migrations.AddField(
            model_name='hizmetdescription',
            name='hizmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hizmet.Hizmet'),
        ),
    ]
