# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='semt',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='ilce',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='mahalle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='posta_kodu',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='sokak',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
